import { useEffect, useRef } from "react";

/**
 * Counter of pending suppressed popstate events.
 * Each suppressedHistoryBack() increments it; each resulting popstate decrements it.
 * Using a counter (vs. a boolean+timer) makes it safe for rapid/concurrent calls.
 */
let suppressCount = 0;

/**
 * Returns true when the next popstate should be ignored because it was
 * triggered programmatically by suppressedHistoryBack().
 * Export so other manual popstate handlers (e.g. order-form) can respect it.
 */
export function isPopstateSuppressed(): boolean {
  return suppressCount > 0;
}

/**
 * Call this instead of raw window.history.back() whenever you want to pop a
 * history entry that YOU pushed (modal open, overlay, etc.) so that other
 * useModalBackButton handlers don't misinterpret the resulting popstate as a
 * real user "back" press and close an unrelated modal.
 */
export function suppressedHistoryBack() {
  suppressCount++;
  window.history.back();
  // Decrement the counter precisely when the resulting popstate fires.
  // Using { once: true } + capture-phase so it runs before bubble-phase handlers.
  window.addEventListener(
    "popstate",
    () => {
      suppressCount = Math.max(0, suppressCount - 1);
    },
    { once: true, capture: true }
  );
}

/**
 * Intercepts the Android/iOS back button (and browser back) to close a modal
 * dialog instead of navigating away from the page.
 */
export function useModalBackButton(isOpen: boolean, onClose: () => void) {
  const historyRef = useRef<{ pushed: boolean; handler: ((e: PopStateEvent) => void) | null }>({
    pushed: false,
    handler: null,
  });
  const onCloseRef = useRef(onClose);
  useEffect(() => { onCloseRef.current = onClose; });

  useEffect(() => {
    if (isOpen) {
      window.history.pushState({ modal: true }, "", window.location.href);
      historyRef.current.pushed = true;

      const onPopState = () => {
        if (suppressCount > 0) {
          // This popstate was generated by suppressedHistoryBack(); ignore it.
          return;
        }
        historyRef.current.pushed = false;
        historyRef.current.handler = null;
        window.removeEventListener("popstate", onPopState);
        onCloseRef.current();
      };

      window.addEventListener("popstate", onPopState);
      historyRef.current.handler = onPopState;

      return () => {
        window.removeEventListener("popstate", onPopState);
      };
    } else {
      const { pushed, handler } = historyRef.current;
      if (handler) {
        window.removeEventListener("popstate", handler);
        historyRef.current.handler = null;
      }
      if (pushed) {
        historyRef.current.pushed = false;
        suppressedHistoryBack();
      }
    }
  }, [isOpen]);
}
